[tool.poetry]
name = "poetry_guard_plugin"
version = "0.1.0"
description = "Plugin for Poetry that wraps dependency installs/updates with a validation process to check for potential supply chain attacks"
authors = []
packages = [{include = "poetry_guard_plugin"}]

[tool.poetry.dependencies]
python = "^3.14"
regex = "*"
poetry = ">=2.0,<3"
guarddog = "^2.10"
aiohttp = "*"
tomlkit = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
pytest-cov = "*"
pytest-asyncio = "*"
flake8 = "*"
mypy = "*"
black = "*"
bandit = {extras = ["toml"], version = "*"}
coverage = {extras = ["toml"], version = "*"}

[build-system]
requires = ["poetry-core>=2.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."poetry.application.plugin"]
poetry-guard = "poetry_guard_plugin.plugin:GuardApplicationPlugin"

[tool.poetry.plugins."poetry_guard.validators.lockfile"]
osv = "poetry_guard_plugin.validators.osv:OsvValidator"
metadata = "poetry_guard_plugin.validators.metadata:MetadataValidator"

[tool.poetry.plugins."poetry_guard.validators.artifact"]
guarddog = "poetry_guard_plugin.validators.guarddog:GuardDogValidator"

[tool.black]
line-length = 120

[tool.mypy]
python_version = "3.14"
strict = true
ignore_missing_imports = true
explicit_package_bases = true
mypy_path = "."

[tool.pytest.ini_options]
testpaths = ["test"]
asyncio_mode = "auto"

[tool.coverage.run]
source = ["poetry_guard_plugin"]
omit = ["test/*"]

[tool.coverage.report]
show_missing = true
